### ISSUE TITLE
error

### ISSUE THREAD

**Issue by a5x** [mqivaUwU/Xbox-Username-Checker#1]
Traceback (most recent call last):
  File "C:\Users\######\Desktop\Xbox-Username-Checker-Latest\Checker.py", line 123, in <module>
    main()
  File "C:\Users\######\Desktop\Xbox-Username-Checker-Latest\Checker.py", line 118, in main
    save_valid_username_to_file(username, length)  # Save the username in real-time
                                ^^^^^^^^
UnboundLocalError: cannot access local variable 'length' where it is not associated with a value

**Comment by mqivaUwU** [comment]
Sorry will fix later <3
